Django 12/accounts/urls.py
from django.urls import path
from .views import index

app_name = 'accounts'
urlpatterns = [
    path('', index, name='index'),
]

Django 12/base/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

from api.models import CategoryResource, TaskResource
from tastypie.api import Api

api = Api(api_name='v1')
category_resource = CategoryResource()
task_resource = TaskResource()

api.register(category_resource)
api.register(task_resource)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('todo/', include('todo.urls')),
    path('', RedirectView.as_view(url="/accounts/", permanent=False)),
    path('accounts/', include('accounts.urls',"accounts")),

    # path('api/', include(category_resource.urls)),
    # path('api/', include(task_resource.urls)),
    path('api/', include(api.urls)),

    

]

Django 12/todo/urls.py
from django.urls import path, include
from . import views

app_name = 'todo'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:task_id>/', views.detail, name='detail'),
    path('<int:task_id>/done/', views.toggle_done, name='toggle_done'),
]

Django 12/accounts/models.py
from django.db import models

# Create your models here.

Django 12/api/models.py
from tastypie.resources import ModelResource
from todo.models import Category, Task
from tastypie.authorization import Authorization



class CategoryResource(ModelResource):
    class Meta:
        queryset = Category.objects.all()
        resource_name = 'categories'
        allowed_methods = ['get']


class TaskResource(ModelResource):
    class Meta:
        queryset = Task.objects.all()
        resource_name = 'tasks'
        allowed_methods = ['get', 'post', 'put', 'delete']
        excludes = ['created', 'updated']
        authorization = Authorization()

    def hydrate(self, bundle):
        bundle.obj.category_id = bundle.data['category_id']
        return bundle

    def dehydrate(self, bundle):
        bundle.data['category_id'] = bundle.obj.category_id
        return bundle

    def dehydrate_name(self, bundle):
        return bundle.data["name"].upper()

Django 12/todo/models.py
from django.db import models
from django.contrib.auth.models import User

class Category(models.Model):
    name = models.CharField(max_length=100)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class Task(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    name = models.CharField(max_length=200, default="")
    is_done = models.BooleanField(default=False)
    description = models.TextField(default='')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

Django 12/accounts/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django import forms
class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Username'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control', 'placeholder':'Password'}))

class RegisterForm(UserCreationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Username'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control', 'placeholder':'Password'}))

Django 12/todo/forms.py
from django import forms
from unicodedata import category

from .models import Task

class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['name','category','description']
        widgets = {
            "name": forms.TextInput(attrs={'class':'form-control', "placeholder":"Task name"}),
            "description": forms.TextInput(attrs={'class':'form-control', "placeholder":"Task description"}),
        }

Django 12/accounts/views.py
from django.shortcuts import render
from django.contrib.auth import login
from django.shortcuts import redirect, render
from accounts.forms import LoginForm, RegisterForm
from django.contrib import messages


def index(request):
    login_form = LoginForm(request=request)
    register_form = RegisterForm()
    next_url = request.GET.get('next') or request.POST.get('next') or "todo:index"
    active_tab = 'login'

    if "login_submit" in request.POST:
        active_tab = 'login'
        login_form = LoginForm(request=request, data=request.POST)
        if login_form.is_valid():
            user = login_form.get_user()
            login(request, user)
            messages.success(request, f'Welcome back, {user.username}!')
            return redirect(next_url)
        messages.error(request, f'Invalid username or password, please try again.!')
    elif "register_submit" in request.POST:
        active_tab = 'register'
        register_form = RegisterForm(request.POST)
        if register_form.is_valid():
            user = register_form.save()
            login(request, user)
            messages.success(request, f'Account created! Welcome, {user.username}!')
            return redirect(next_url)
        messages.error(request, f'Register failed! Please try again later.')
    return render(request, "auth.html",{
        "login_form": login_form,
        "register_form": register_form,
        "active_tab": active_tab,
        "next_url": next_url,
    })

Django 12/api/views.py
from django.shortcuts import render

# Create your views here.

Django 12/todo/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, Http404
from django.contrib import messages

from . import models
from .forms import TaskForm

# @login_required
def index(request):
    # return HttpResponse("todo")
    # return HttpResponse([str(task) +'<br/>' for task in tasks])
    if request.method == "POST":
        form = TaskForm(request.POST)
        if form.is_valid():
            task = form.save(commit=False)
            task.owner = request.user
            task.save()
            messages.success(request, "Task added successfully")
            return redirect('todo:index')
    else:
        form = TaskForm()

    tasks = models.Task.objects.order_by("-id")
    return render(request, 'tasks.html', {'tasks':tasks, 'form':form})

# @login_required
def detail(request, task_id):
    # variant 1
    # try:
    #     task = models.Task.objects.get(pk=task_id)
    #     return render(request, 'detail.html', {'task':task})
    # except models.Task.DoesNotExist:
    #     raise Http404
    # variant 2
    task = get_object_or_404(models.Task, pk=task_id, owner=request.user)
    return render(request, 'detail.html', {'task':task})

# @login_required
def toggle_done(request, task_id):
    task = get_object_or_404(models.Task, pk=task_id, owner=request.user)
    task.is_done = request.POST.get('is_done') == '1'
    task.save()
    return redirect("todo:index")

Django 12/templates/auth.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'todo/css/auth.css' %}">
</head>
<body>

<div class="container" id="container">
	<div class="form-container sign-up-container">
		<form method="get" action="{% url 'accounts:index'  %}">
			<h1>Create Account</h1>
			{% csrf_token %}
            {{ register_form.username }}
            {{ register_form.password }}
			<button type="submit" name="register_submit">Sign Up</button>
		</form>
	</div>
	<div class="form-container sign-in-container">
		<form method="get" action="{% url 'accounts:index' %}">
			<h1>Sign in</h1>
			{% csrf_token %}
            {{ login_form.username }}
            {{ login_form.password }}
			<button type="submit" name="login_submit">Sign In</button>
		</form>
	</div>
	<div class="overlay-container">
		<div class="overlay">
			<div class="overlay-panel overlay-left">
				<h1>Welcome Back!</h1>
				<p>To keep connected with us please login with your personal info</p>
				<button class="ghost" id="signIn">Sign In</button>
			</div>
			<div class="overlay-panel overlay-right">
				<h1>Hello, Friend!</h1>
				<p>Enter your personal details and start journey with us</p>
				<button class="ghost" id="signUp">Sign Up</button>
			</div>
		</div>
	</div>
</div>
<script src="{% static 'todo/js/auth.js' %}"></script>
</body>
</html>

Django 12/templates/detail.html
{% extends "layout.html" %}

{% block title %}
    Task: {{ task.name }}
{% endblock %}

{% block content %}
    <div class="card shadow-sm border-0 my-3" style="max-width: 30rem;">
  <div class="card-body">
    <h5 class="card-title fw-bold">{{ task.name }}</h5>
    <p class="card-subtitle text-muted mb-2">
      <i class="bi bi-folder2-open"></i> Category: {{ task.category }}
    </p>
    <p class="card-text">{{ task.description }}</p>
    <a href="#" class="btn btn-primary btn-sm">
      <i class="bi bi-pencil-square"></i> Edit
    </a>
    <a href="#" class="btn btn-danger btn-sm">
      <i class="bi bi-trash"></i> Delete
    </a>
  </div>
</div>

{% endblock %}

Django 12/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
        {% endblock %}
    </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js" integrity="sha384-FKyoEForCGlyvwx9Hj09JcYn3nv7wiPVlz7YYwJrWVcXK/BmnVDxM+D2scQbITxI" crossorigin="anonymous"></script>
</head>
<body>
<nav class="navbar navbar-expand-lg bg-dark border-bottom border-body" data-bs-theme="dark">
  <div class="container-fluid">
    <a href="{% url 'todo:index' %}" class="navbar-brand ms-4 fw-bold text-light text-decoration-none">
      <i class="bi bi-check2-circle me-2"></i>ToDo
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarMenu"
      aria-controls="navbarMenu" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse justify-content-end" id="navbarMenu">
      <ul class="navbar-nav me-4">
        <li class="nav-item">
          <a href="/admin/" class="nav-link text-light">
            <i class="bi bi-person-gear me-1"></i>Admin
          </a>
        </li>
        <li class="nav-item">
          <a href="/api/v1/" class="nav-link text-light">
            <i class="bi bi-code-slash me-1"></i>API
          </a>
        </li>
      </ul>
    </div>
  </div>
</nav>

    <main class="container">
        {% block content %}
        {% endblock %}
    </main>

</body>
</html>

Django 12/templates/tasks.html
{% extends 'layout.html' %}

{% block title %}
    ToDo Tasks
{% endblock %}

{% block content %}
    <div class="container mt-4">
        <h2 class="mb-3">Task List</h2>

       <!-- Аккордеон-карточка для формы -->
<div class="accordion mb-4" id="todoAccordion">
  <div class="accordion-item shadow-sm rounded-3 overflow-hidden">
    <h2 class="accordion-header" id="addTaskHeading">
      <button class="accordion-button {% if not form.errors %}collapsed{% endif %}" type="button"
              data-bs-toggle="collapse"
              data-bs-target="#addTaskCollapse"
              aria-expanded="{% if form.errors %}true{% else %}false{% endif %}"
              aria-controls="addTaskCollapse">
         Добавить задачу
      </button>
    </h2>

    <div id="addTaskCollapse"
         class="accordion-collapse collapse {% if form.errors %}show{% endif %}"
         aria-labelledby="addTaskHeading" data-bs-parent="#todoAccordion">
      <div class="accordion-body">
        <form method="post" action="{% url 'todo:index' %}" class="row g-3">
          {% csrf_token %}

          {% if form.non_field_errors %}
            <div class="col-12">
              <div class="alert alert-danger py-2 mb-0">
                {{ form.non_field_errors }}
              </div>
            </div>
          {% endif %}

          <div class="col-md-4">
            <label for="id_name" class="form-label">Название</label>
            {{ form.name }}
            {% if form.name.errors %}
              <div class="invalid-feedback d-block">{{ form.name.errors|striptags }}</div>
            {% endif %}
          </div>

          <div class="col-md-4">
            <label for="id_category" class="form-label">Категория</label>
            {{ form.category }}
            {% if form.category.errors %}
              <div class="invalid-feedback d-block">{{ form.category.errors|striptags }}</div>
            {% endif %}
          </div>

          <div class="col-md-4">
            <label for="id_description" class="form-label">Описание</label>
            {{ form.description }}
            {% if form.description.errors %}
              <div class="invalid-feedback d-block">{{ form.description.errors|striptags }}</div>
            {% endif %}
          </div>

          <div class="col-12 d-flex gap-2">
            <button type="submit" class="btn btn-success">Сохранить</button>
            <button type="button" class="btn btn-outline-secondary"
                    data-bs-toggle="collapse" data-bs-target="#addTaskCollapse">
              Скрыть
            </button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

        <table class="table table-striped table-bordered table-hover align-middle shadow-sm rounded">
            <thead class="table-dark">
            <tr>
                <th scope="col">Name</th>
                <th scope="col">Category</th>
                <th scope="col">Description</th>
                <th scope="col">Done</th>
            </tr>
            </thead>
            <tbody>
            {% for task in tasks %}
                <tr>
                    <td>
                        {#                    <a href="{{ task.id }}" class="text-decoration-none">#}
                        {#                        {{ task.name }}#}
                        {#                    </a>#}
                        {#                    #}
                        {#                     <a href="{% url 'detail' task.id %}" class="text-decoration-none">#}
                        {#                        {{ task.name }}#}
                        {#                    </a>#}

                        <a href="{% url 'todo:detail' task.id %}" class="text-decoration-none">
                            {{ task.name }}
                        </a>

                    </td>
                    <td>{{ task.category }}</td>
                    <td>{{ task.description }}</td>


                    <td class="text-center">
                        <form method="post" action="{% url 'todo:toggle_done' task.id %}">
                            {% csrf_token %}
                            <input type="hidden" name="is_done" value="0">
                            <input
                                    type="checkbox"
                                    class="form-check-input"
                                    name="is_done"
                                    value="1"
                                    {% if task.is_done %} checked {% endif %}
                                    onchange="this.form.submit()"
                            >
                        </form>
                    </td>
                </tr>
            {% empty %}
                <tr>
                    <td colspan="4" class="text-center text-muted">Задач пока нет</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}