Django 08/base/urls.py
from django.urls import path, include
from django.contrib import admin


urlpatterns = [
       path('admin/', admin.site.urls),
    path('todo/', include('todo.urls')),
    path('', include('todo.urls')),
]

Django 08/todo/urls.py
from django.urls import path
from . import views

app_name = 'todo'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:task_id>', views.detail, name='detail'),
]

Django 08/todo/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404
from . import models


def index(request):
    # return HttpResponse("todo")
    tasks = models.Task.objects.all()
    # return HttpResponse([str(task) +'<br/>' for task in tasks])
    return render(request, 'tasks.html', {'tasks':tasks})

def detail(request, task_id):
    # variant 1
    # try:
    #     task = models.Task.objects.get(pk=task_id)
    #     return render(request, 'detail.html', {'task':task})
    # except models.Task.DoesNotExist:
    #     raise Http404
    # variant 2
    task = get_object_or_404(models.Task, pk=task_id)
    return render(request, 'detail.html', {'task':task})

Django 08/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
        {% endblock %}
    </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossorigin="anonymous">
</head>
<body>
<nav class="navbar bg-dark border-bottom border-body" data-bs-theme="dark">
  <div class="container-fluid">
    <a href="{% url "todo:index" %}" class="navbar-brand ms-5 fw-bold text-decoration-none text-light">
      ToDo
    </a>
  </div>
</nav>
    <main class="container">
        {% block content %}
        {% endblock %}
    </main>

</body>
</html>

Django 08/templates/tasks.html
{% extends 'layout.html' %}

{% block title %}
    ToDo Tasks
{% endblock %}

{% block content %}
<div class="container mt-4">
    <h2 class="mb-3">Task List</h2>
    <table class="table table-striped table-bordered table-hover align-middle shadow-sm rounded">
        <thead class="table-dark">
            <tr>
                <th scope="col">Name</th>
                <th scope="col">Category</th>
                <th scope="col">Description</th>
                <th scope="col">Done</th>
            </tr>
        </thead>
        <tbody>
            {% for task in tasks %}
            <tr>
                <td>
{#                    <a href="{{ task.id }}" class="text-decoration-none">#}
{#                        {{ task.name }}#}
{#                    </a>#}
{#                    #}
{#                     <a href="{% url 'detail' task.id %}" class="text-decoration-none">#}
{#                        {{ task.name }}#}
{#                    </a>#}
                    
                    <a href="{% url 'todo:detail' task.id %}" class="text-decoration-none">
                        {{ task.name }}
                    </a>
                    
                </td>
                <td>{{ task.category }}</td>
                <td>{{ task.description }}</td>
                <td class="text-center">
                    <input class="form-check-input" type="checkbox" {% if task.is_done %}checked{% endif %}/>
                </td>
            </tr>
            {% empty %}
            <tr>
                <td colspan="4" class="text-center text-muted">Задач пока нет</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}